trigger:
  branches:
    include:
    - master
    - develop
pr:
 branches:
   include:
   - master
   - develop
   
variables:
  - name: ArtifactName
    value: Packages

stages:
- stage: Build
  jobs:
  - job: Windows

    pool:
      vmImage: 'windows-latest'

    variables:
    - name: PackageOutputPath
      value: $(Build.ArtifactStagingDirectory)

    steps:
    - task: gitversion/setup@0
      inputs:
        versionSpec: '5.X'
      displayName: 'Install GitVersion'

    - task: gitversion/execute@0
      inputs:
        useConfigFile: true
        configFilePath: 'gitversion.yml'
      displayName: 'Calculate version'

    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: 6.1.0

    - task: NuGetCommand@2
      inputs:
        command: restore
        restoreSolution: src/Nimue.sln

    - task: MSBuild@1
      inputs:
        msbuildLocationMethod: version
        msbuildVersion: latest
        configuration: Release
        platform: Any CPU
        msbuildArguments: /p:PackageVersion=$(GitVersion.SemVer)

    - task: PublishBuildArtifacts@1
      inputs:
        ArtifactName: $(ArtifactName) 

- stage: Release
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - job: NuGet_Internal

    pool:
      vmImage: 'windows-latest'
  
    steps:
    - checkout: none

    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: current
        downloadType: single
        artifactName: $(ArtifactName)

    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: 6.1.0
    
    - task: NuGetCommand@2
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/$(ArtifactName)/*.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'NuGet.org - nventive'
