trigger:
  branches:
    include:
    - master
    - develop

variables:
  - name: ArtifactName
    value: Packages

stages:
- stage: Build
  jobs:
  - job: Windows

    pool:
      vmImage: 'windows-latest'

    variables:
    - name: PackageOutputPath
      value: $(Build.ArtifactStagingDirectory)

    steps:
    - task: GitVersion@5
      inputs:
        runtime: 'core'
        configFilePath: 'gitversion.yml'

    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: 5.1.0

    - task: NuGetCommand@2
      inputs:
        command: restore
        restoreSolution: src/Nimue.sln

    - task: MSBuild@1
      inputs:
        msbuildLocationMethod: version
        msbuildVersion: latest
        configuration: Release
        platform: Any CPU
        msbuildArguments: /p:PackageVersion=$(GitVersion.SemVer)

    - task: PublishBuildArtifacts@1
      inputs:
        ArtifactName: $(ArtifactName) 

- stage: Release
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - job: NuGet_Internal
  
    steps:
    - checkout: none

    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: current
        downloadType: single
        artifactName: $(ArtifactName)

    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: 5.4.0
    
    - task: NuGetCommand@2
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/$(ArtifactName)/*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: 'nventive'